name: Docker image
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
        run: sh ci/build-app.sh
      - name: Test
        run: sh ci/unit-test-app.sh